---
name: Format CSVs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r linters/requirements.txt
      - run: python linters/format.py
      - run: python linters/validate.py
      - run: |
          git config user.name 'Jon Banafato'
          git config user.email 'jonafato@users.noreply.github.com'
          git diff --quiet || git commit -am "Autoformat CSVs"
          git push
