---
name: Validate CSV
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r linters/requirements.txt
      - run: python linters/autoformat-csv.py
      - run: python linters/lint-csv.py
      - run: |
          git config user.name 'Jon Banafato'
          git config user.email 'jonafato@users.noreply.github.com'
          git diff --quiet || git commit -am "Autoformat CSV"
          git push
