---
name: Validate CSV
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r linters/requirements.txt
      - run: python linters/autoformat-csv.py
      - run: python linters/lint-csv.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Autoformat CSV
          commit_user_name: Jon Banafato
          commit_user_email: jonafato@users.noreply.github.com
          commit_author: Jon Banafato <jonafato@users.noreply.github.com>
